title: Swapnil Singh
email: swappp7singh@gmail.com
description: Hi. I'm Swapnil. I'm a Software Engineer by profession. I like travelling, listening to good music, watching hollywood movies, coding & building stuff from scratch.
baseurl: ''
url: ''
twitter_username: an0nh4x0r
github_username: an0nh4x0r
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
